version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - journal-network

  frontend:
    build:
      context: ./frontend/my-react-app/harshsirnebanwaya
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - journal-network

networks:
  journal-network:
    driver: bridge
