version: '3.8'

services:
  journal-backend:
    build: .
    container_name: journal-backend
    ports:
      - "8080:8080"
    volumes:
      - journal_data:/data
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/journal/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  journal_data:
    driver: local
